require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'callin' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'callinTests' do
    inherit! :complete
    # Pods for testing
    # Latest version of the sdk is 3.0.2, maybe I should consider updating 🤔
    pod 'JitsiMeetSDK','2.6.0'
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'callin-tvOS' do
  # Pods for callin-tvOS

  target 'callin-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
